project:
  type: website
  output-dir: docs

website:
  title: "scuartasr.github.io"
  navbar:
    right:
      - about.qmd
      - icon: briefcase
        href: scuartasr.quarto.pub/
      - icon: linkedin
        href: https://linkedin.com/scuartasr/
      - icon: github
        href: https://github.com/scuartasr/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

