project:
  type: website
  output-dir: docs

website:
  title: "Simón Cuartas"
  navbar:
    right:
      - about.qmd
      - icon: briefcase
        href: https://scuartasr.quarto.pub/
      - icon: linkedin
        href: https://www.linkedin.com/in/scuartasr/
      - icon: github
        href: https://github.com/scuartasr/
format:
  html:
    theme: sandstone
    css: styles.css

editor: visual

